### PR TITLE
Extending comment scanning to resolve #24

### LINKED ISSUE #24: Parsing silently fails in case text between entries in bibfile
In case where there is text outside of entries, parsing silently fails and no entries are parsed. Example, which delivers 0 entries after parsing:

```
% Encoding: UTF-8
@article{CitekeyArticle,
  author   = "John Doe",
  title    = "The independence of the continuum hypothesis",
  journal  = "Proceedings of the National Academy of Sciences",
  year     = 1963,
  volume   = "50",
  number   = "6",
  pages    = "1143--1148",
}
```
While I do not see any reason for text outside of entries, it appears some bibliography tools are adding other forms of comments nevertheless. While this is considered garbage from a BibTeX/BibLaTeX point of view, they are still able to process the entries anyway.

Specifications seem to allow text between entries as well, e.g. see: https://tex.stackexchange.com/questions/21709/comments-in-bibtex
and section 4.7: https://texdoc.org/serve/btxdoc/0

This parser should either throw an error on parsing or discard any text between entries.

### PR DESCRIPTION
**Pull request by anthonygam**
Hello @nickng, this project has been very useful for me with formatting my honours thesis, so thank you for maintaining it!

I have been looking into #24. For now, I've just written a unit test reproducing the issue, which fails on my machine. I also tried logging `s.String()` and it appears to be completely empty.

I would like to try to solve the bug over the next few days. Please let me know if this is welcome, if I've made any mistakes with my test, or if you have any suggestions about how to approach fixing the bug.

### CODE REVIEW

**Comment by anthonygam** [comment]
So far, I have a very simple fix that does not modify the existing grammar. Please let me know if you would prefer a different approach.

File: scanner.go [hunk 1]
```diff
@@ -13,13 +13,14 @@ var parseField bool
 // scanner is a lexical scanner
 type scanner struct {
 	commentMode bool
+	ignoreMode  bool
```
Comment (nickng) [inline scanner.go:16]: I wonder if it's better to call this "outsideEntry" or something like that to be clear that we're not switching into a different context mode (comment mode is when we're scanning comments, not affected by the grammar), but actually not inside an entry so we can ignore everything.

**Review by nickng — COMMENTED** [review]
I think this looks good! Just a small comment on the variable name.
I start to think whether it's worth support parsing of comments too down the line, so we don't just strip out comments but can also put them back. :thinking:

File: scanner.go (hunk 1 above)
Comment (anthonygam) [reply scanner.go]: I think that's a great idea, definitely a much clearer name. I've updated it in a new commit.

**Comment by anthonygam** [comment]
> I think this looks good! Just a small comment on the variable name. I start to think whether it's worth support parsing of comments too down the line, so we don't just strip out comments but can also put them back. 🤔

Oh that's an interesting idea! Are you thinking of doing this with @comment{...} text, or with all the text in between entries? If it's the latter, then maybe this PR would require a refactor right?
